sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle persistent_message/ --exclude=migrations
- jshint persistent_message/static/persistent_message/js/ --verbose
- python -m compileall persistent_message/
- coverage run --source=persistent_message/ manage.py test persistent_message
after_success:
- coveralls
before_deploy:
- find persistent_message/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > persistent_message/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: nXbpBvjrjPZNn/QOi17Fek+qraXiwF2mUkDAcaG0E1GZM3CAzimLpeKniibiRlactE6efpPpAL5jUAO/PywmEJ8gDwdRvnyKG/BW5MdB1dQ0L6nVDumGo8Uwe9irKWAzSB6PfIV5CeRm1lrzN1hZhiP6gkinqvuUfm2Kx2WJ71sm3ul9M+HZLFJzKbT7TFCDv6ukUgRItZ/Y2A98/elVZ2HF0MpQsJmaR2lBi89aXyTQ3ynj8nn02EoB4n4JCBlpXKeFXpjTO4GquB+8jYGc7uXeEXuaa3wBozLBg93AExCVdR3qty4viYfnDKDUaWLSNCHF4QJtSMBhrAdXVAKCDy/l1d/HY7BWLntgK7HVw9dlYduApK8vKkErYbHpMwl/bfvVnslni6+g1ZsUKkXbWxVQTdbfFX3ztkLFaSX74iXApDOBr4iVWrRin89R7QwJMmEzXkQIaw3fafUWtQ2JGW26Dg9DlHhwaPJshSSxgtsHsdtXeGnowHU3GVsFus+dErmMGqGJ1BUv06pVWfPKBauOQh0bcr3RKcaLuGCk6RN4Tbc+o4HDeYUqGBXBwrSqDllJKhAHXTBIOb4u+eSkJHVvWqh36RD2c91Asst9scHdFeb3G13DerWzWNOZkUpsEHOZ7UcQzmvtWKQo6gasn0ouuUIvkQXKkMTWsKOVul8=
  on:
    tags: true
    python: '3.6'
