sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle persistent_message/ --exclude=migrations
- jshint persistent_message/static/persistent_message/js/ --verbose
- python -m compileall persistent_message/
- coverage run --source=persistent_message/ manage.py test persistent_message
after_success:
- coveralls
before_deploy:
- find persistent_message/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > persistent_message/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: GYTGdp5oQqzC+IWA2Daith73VyK6KdvjMi7AJsp9L7fxcCBu0aOM8l4UVnMLbm7r6KDUVFjqn91+S/7B8/oDsARe+VAj8cIubLvYDS1VOZRzhsEjeNWbTgpGKXlUsEqyczk/5jDBFvHFk0OJupnIawezrAGioAYttTsPdchC8PBS3F9acDSMYCK3UHMuOOYfz4PIuqDu0k3cRnTvVoTRHdG5lHTnNqQeHASWCqpPmIyOLb3iBFa0PUBk6aM1LVWVwqbH6+gWNEx0nBuFj5Fcr82sLdufnYjTmJscs7EJPnDAaVM7UUFsE0YDxtgmt/KzFeRPKgTCuhEsasVPqeFQThwOok67MDIQEFbi0MDBoDzgu0Mgyq4NVEata3ejLl9MVNmpR3iTBawJ9wWOBl8XoOM3QT1kaNjQxwnRBpXwRcYwrBjeCEedCFxPy4L54Xe5ssXYpFHNhByLS/+vH06G73XzIJoMJMmzXQkL6Hq61HV6Lxl7jAzRlA+rqVoG/msJHdyWrG0tE2hJGdaYxxRb5QR/yMJzVBMYeXcJCKQXaXvf8Atf0c8S2P3nudwqc4GsoxxLDgbl2mXxPzWRzSpQux4qj5vzn/u3oc/ccaDm5EbAXsZCyE8WSrzebXeSpoRWC6ptnqlUOSrZeXahpDxF3lt/cCmsgkP/aEL/lszgV4c=
  on:
    tags: true
    python: '3.6'
