sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle persistent_message/ --exclude=migrations
- jshint persistent_message/static/persistent_message/js/ --verbose
- python -m compileall persistent_message/
- coverage run --source=persistent_message/ manage.py test persistent_message
after_success:
- coveralls
before_deploy:
- find persistent_message/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > persistent_message/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: YtDae5a0F6Fi3Bq2C5XRG/7/e8awpaMMmXLYme+8YOunrBJGZx0WONmvM+TPFfhRolRAakJDk1FYyGDGxmgfPUEzSi9IrZYL2S9CTciZJ8kDhcleZU+p2MYPKzGdFFh798CnU7FMdGtBMVGvTG7Ie+RfB6HV8uB2Gz7gthcLaR9D4WXB4YjHUf1EIKZM4QZKXzoezLM4jx1HBxbwUuXzD0lPSfFWN6WKfQHihNRPZdnsOBIsgV5vgf4tSM2iTiOzFKlpGfQNYjDiu0onu2QSOdJEXkix2SueS+Vku+FucFyYtAKbaGK+W+Mx354xBDK7BTcYkYN6vQLl0W/rjFCwOX6m+f+JkVQrCzVUR7KHEhiAb/uOX9hE2IYAGdqcqU8fwEqwO2dzr946bsW8ZGN3lAkrNr+aATXTm4ojHkNNiLtNOcYumskMACSPpn4Uh6lSFWKqFG+muyeQTTyBNtv9Ps//+XI0LeP92i1ko6CKHCq3utJs7bUN+AxAU63uTaK/adAbqx0EmVcm0QNYg4ArOsM5X1JwkT8NWxDpTA+EgwN2JCZdNq9T+BDJJ8WCLp5efgMAEbLszGy9JrLdT3m+D8lUXXTXmcn2g5+wd7DocUxfNL9At3ric2RvqqJvTNYh7yumNjEPuK+y1cOVU8t7GrdMiD/5XPe+AA3+wpRJMog=
  on:
    tags: true
    python: '3.6'
