sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle persistent_message/ --exclude=migrations
- jshint persistent_message/static/persistent_message/js/ --verbose
- python -m compileall persistent_message/
- coverage run --source=persistent_message/ manage.py test persistent_message
after_success:
- coveralls
before_deploy:
- find persistent_message/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > persistent_message/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: TGrOGTnr0X9FW8ZNMJGCaDcO+sc2Lbo64bUnQeAPM4mBBVR8CB8PcUo4G/DKJ46ga3LCKeaMzOp2lceubYAKcKkHf2fJ+CZntKkUB4x7EwvXndQnWqRWtJsJKtyZ/6RlnGDCV7Rl/3LroVZ11rJc9lFkLxD2SC8RKp5OC9AW9yOsQ6Ka8+VoOvn/W8jCl8DjO15Y79IBl6rRy/87tpYKci/ldmj4JehV+RdzLgB98V3UWsWTn0+WEcagH0QqTiocCSfG+ik8E/c+DqWBFe6e2rmF6igE3loB8VCwCTTTRupsd7FOu/vk4P2NkpDQLmH8EuPU3qPhyOaKFjY6RbcuzQ6n4yQNSDCdjv83awq2JeqWo++zgb4EZCnJXmgpUhSBfdxHaSXbi+34Uk8lCh5mFTfQlDST14Y8yeM72wymjFYOqzJ54rs/5ep6ztCnVGU6KsDFHbYbLJ32mevFYzSQG1J67fRtPiPLYLACQ+S4FOEVEOX4uIVPETXRFVw0oEyXoYAsBn/qtsD684YxevTQyD5+U0Twry4abJBP04FDlwgpOaadN6RaVLdAEUA96631w16PV4KSDwIJkXMd9RLM2TOd7TkdXZ6dRfI+iubPc/lLOQPOiokN4HtxTHtqvCem8taKjKnMzFN2i1A4xmfBvLMNPSpNKYw9XbTm3CUeEak=
  on:
    tags: true
    python: '3.6'
