sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py
script:
- pycodestyle persistent_message/ --exclude=migrations
- jshint persistent_message/static/persistent_message/js/ --verbose
- python -m compileall persistent_message/
- coverage run --source=persistent_message/ manage.py test persistent_message
after_success:
- coveralls
before_deploy:
- find persistent_message/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > persistent_message/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: SGBDUnH3MeqnQBlWIyXp+Lnjbse5zQMry/Dm2rmHn86T+ugX/3tnNIGLu2yBQEskQdtco7TcHxWRMuIv/UcbPFJfI8srkjEM67NG/nPYO86JfXdegY24eQfZtDYmHkOcdLhUIL+vSLYp9v5/VhaFGE7Ui1wKF+r8f7XOSTLS16dZLv+6Wdiwfcd8f4ZevJM7WN+h3x38jlapd42vC1ydDSUbvgAA5d7Fsq8P4fGPJjqU0PFVl/6Miw+TxEvxlxD0jqiZ63WqvZ/5A1w+dwj8PLh1bihB/DIYtTr8xq9+DWX0xgxhAHcmPeEz77OhG6X9dEEjnS3Oh7mzUMiAIAbM6kBbdvzdnKYOreBWu3l4jlmAOLdEGY8bCRI3VfepNCjT+o/CguklpKGLxCgX6/DXfL9PYkufkVxCn14EKRQ3HOHApu5uQVZ5wwbQIpyi3gz59OrDRCIaL6azMCoSVbQhrdjPlRnbR28YOPEa2/jx7xQqjbdwnM8CV5ptTfHqk2dj0pThbdFc4XvmMCdRgk3NfPg3LubBlMfHFXoH7BrPYu2OEvnEaGnz3uBc4Gr4+n4zrXRGLG0kjXQkkesTn9ODaa5F7a1VgJ0R6ggj/dvqiAF7DMGEdrGJKRTYigRf7ba3LG+h8VBl2x2DqQnKCp8PBw9ocMJz0g0xpvDcPJui+Ks=
  on:
    tags: true
    python: '3.6'
