# Generated by Django 3.2.13 on 2022-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistent_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
